FROM ubuntu@sha256:6f6ec53d36a9504f01e3636cf68e0e03761a3b6947a95ba430ae553ee3aaf4d9

# renovate: datasource=github-tags depName=apache/tomcat
ENV TOMCAT_VERSION 8.5.90
ENV TOMCAT_TGZ_URL https://repository.apache.org/content/repositories/releases/org/apache/tomcat/tomcat/$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz
