FROM ubuntu@sha256:b060fffe8e1561c9c3e6dea6db487b900100fc26830b9ea2ec966c151ab4c020

# renovate: datasource=github-tags depName=apache/tomcat
ENV TOMCAT_VERSION 8.5.90
ENV TOMCAT_TGZ_URL https://repository.apache.org/content/repositories/releases/org/apache/tomcat/tomcat/$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz
