FROM ubuntu@sha256:b2175cd4cfdd5cdb1740b0e6ec6bbb4ea4892801c0ad5101a81f694152b6c559

# renovate: datasource=github-tags depName=apache/tomcat
ENV TOMCAT_VERSION 8.5.92
ENV TOMCAT_TGZ_URL https://repository.apache.org/content/repositories/releases/org/apache/tomcat/tomcat/$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz
