FROM ubuntu@sha256:81bba8d1dde7fc1883b6e95cd46d6c9f4874374f2b360c8db82620b33f6b5ca1

# renovate: datasource=github-tags depName=apache/tomcat
ENV TOMCAT_VERSION 8.5.90
ENV TOMCAT_TGZ_URL https://repository.apache.org/content/repositories/releases/org/apache/tomcat/tomcat/$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz
